page_title = "TESTING MATURITY ASSESSMENT"
process_type = ["QA PROCESS", "AUTOMATION TESTING","DATABASE TESTING",
                "PERFORMANCE TESTING"]
tab_titles = [ "DASHBOARD", "MATURITY ASSESSMENT",  
              "PENDING AREAS / GAPS", "DATA PREVIEW"]