page_title = "QA PROCESS & AUTOMATION TESTING MATURITY ASSESSMENT"
process_type = ["QA PROCESS", "AUTOMATION PROCESS"]
tab_titles = [ "DASHBOARD", "MATURITY ASSESSMENT",  
              "PENDING AREAS / GAPS", "DATA PREVIEW"]